### PR TITLE
Next web clone

### PR DESCRIPTION
**Pull request by Teshager21**
Activate a stickler file

### CODE REVIEW

**Comment by Teshager21** [comment]
-we used a mobile-first approach with our media queries and used a grid to make the page responsive
-used two breakpoints:- one for tablet and another for desktop
-extensive use of background images and gradients
-downloaded and used the same fonts

**Comment by lucasmazo32** [comment]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. The README file is great and the webpage looks almost identical.

For the project to get approved kindly implement these changes:

- [x] When the logo is on the main article, it should not be displayed in the navbar. 

image

- [x] The hamburger icon on the original webpage only appears after everything is hidden. It should not appear if the text is displayed.

[Your page] image

[The Next Web page] image

- [x] I see that the lintern file is different from the one provided by microverse. Please copy this [code](https://github.com/microverseinc/linters-config/blob/master/css/stylelint.config.js) to your stylelint.config.js file.

Almost there, remember that:
> *"Success is the sum of small efforts, repeated day in and day out."* - Robert Collier

### Happy coding! :computer:

## Lucas Mazo

**Comment by JasemDuncan** [comment]
# Hi Lucas Mazo

Thank you very much for your advice, we changed all the points that you request.
Happy coding too friend.
💻!

**Comment by trekab** [comment]
# Approved! :tada:
Congratulations @Teshager21 and @JasemDuncan :clap: You have done a great job implementing all the required changes.

_Goodluck on your next projects!_
__Treasure Kabareebe__

**Pull request merged**
